<?php

/**
 * Created by PhpStorm.
 * Usuario: Vinicius
 * Date: 09/09/14
 * Time: 00:44
 */
class ExceptionMsg
{
    private static $constraints = array(
        '08006' => 'Impossível conectar. Senha incorreta?',
        'Not null violation' => 'Violação de restrição de campo vazio. Verifique se não esqueceu de inserir alguma informação Obrigatória.',
        'pk_tb_apartamento_cd_apartamento' => 'Erro no código de apartamento.',
        'pk_tb_categoria_cd_categoria' => 'Erro no código de categoria.',
        'pk_tb_cd_vl_categoria_cd_vl_categoria' => 'Erro no código de valor de categoria.',
        'pk_tb_condominio_cd_condominio' => 'Erro no código de condomínio.',
        'pk_tb_itens_orcamento_nr_sequencia' => 'Erro no código de itens de orçamento.',
        'pk_tb_morador_endereco_nr_sequencia' => 'Erro no código de endereço de morador.',
        'pk_tb_cd_ocorrencia_cd_pessoa_fisica' => 'Erro no código pessoa relacionada a ocorrência.',
        'pk_tb_ocorrencia_cd_ocorrenica' => 'Erro no código de ocorrência.',
        'pk_tb_orcamento_cd_orcamento' => 'Erro no código de orçamento.',
        'pk_tb_ordem_servico_cd_ordem_servico' => 'Erro no código de ordem de serviço.',
        'pk_tb_pessao_fisica_cd_pessoa_fisica' => 'Erro no código de pessoa física.',
        'uq_tb_pessoa_fisica_cpf' => 'O CPF informado já existe em outro cadastro!',
        'uq_tb_pessoa_fisica_rg' => 'O RG informado já existe em outro cadastro!',
        'uq_tb_pessoa_fisica_email' => 'O e-mail informado já existe em outro cadastro de pessoa física!',
        'pk_tb_pessao_juridica_cd_pessoa_juridica' => 'Erro no código de pessoa jurídica.',
        'uq_tb_pessoa_juridica_cgc' => 'O CNPJ informado já existe em outro cadastro!',
        'uq_tb_pessoa_juridica_email' => 'O e-mail informado já existe em outro cadastro de pessoa jurídica!',
        'pk_tb_pf_endereco_nr_sequencia' => 'Erro no código de endereço de pesssoa física.',
        'pk_tb_pj_endereco_nr_sequencia' => 'Erro no código de endereço de pessoa jurídica.',
        'pk_tb_profissao_cd_profissao' => 'Erro no código de profissão.',
        'pk_tb_relacionados_cd_pessoa_fisica_1_cd_pessoa_fisica_2' => 'Erro no código de pessoa física.',
        'pk_tb_servico_adicional_cd_serv_adicional' => 'Erro no código de serviço adicional.',
        'pk_tb_setor_cd_setor' => 'Erro no código de setor.',
        'pk_tb_usuario_cd_usuario' => 'Erro no código de usuário.',
        'pk_tb_vaga_garagem_cd_vaga' => 'Erro no código de vaga de garagem.',
        'pk_tb_pf_telefone_cd_pf_fone' => 'Erro no código de telefone de pessoa física.',
        'pk_tb_pj_telefone_cd_pj_fone' => 'Erro no código de telefone de pessoa jurídica',
        'pk_tb_instituicao_ensino_cd_instituicao' => 'Erro no código de instituição de ensino.',
        'fk_tb_instituicao_ensino_cd_catg_instituicao' => 'Erro no código de categoria de instituição de ensino.',
        'fk_tb_pf_telefone_cd_catg_fone_pf_cd_vl_catg_fone_pf' => 'Erro no código de valor de categoria de telefone de pessoa física.',
        'fk_tb_pj_telefone_cd_catg_fone_pj_cd_vl_catg_fone_pj' => 'Erro no código de valor de categoria de telefone de pessoa jurídica.',
        'fk_tb_pessoa_fisica_cd_catg_org_rg_cd_vl_catg_org_rg' => 'Erro no código de valor de categoria de estado emissor do RG.',
        'fk_tb_pessoa_fisica_cd_catg_grau_ensino_cd_vl_catg_grau_ensino' => 'Erro no código de valor de categoria de grau de ensino.',
        'fk_tb_servico_adicional_cd_pessoa_fisica' => 'Erro no código de serviço adicional relacionado a pessoa física.',
        'fk_tb_servico_adicional_cd_catg_servico_cd_catg_vl_servico' => 'Erro no código de valor de categoria de seviço adicional.',
        'fk_tb_pessoa_fisica' => 'Erro no código fk de pessoa física.',
        'fk_tb_pj_telefone' => 'Erro no código fk de telefone de pessoa jurídica.',
        'fk_tb_pf_telefone' => 'Erro no código fk de telefone de pessoa física.',
        'fk_tb_vaga_garagem_cd_setor' => 'Erro no código de vaga de garagem.',
        'fk_tb_usuario_cd_pessoa_fisica' => 'Erro no código fk de usuário',
        'fk_tb_setor_cd_condominio' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_setor_cd_condominio ao suporte. Informe o código ao suporte.',
        'fk_tb_servico_adicional_cd_ordem_servico' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_servico_adicional_cd_ordem_servico ao suporte.',
        'fk_tb_servico_adicional_cd_setor' => 'Algo terrível aconteceu!! :-( Informe o fk_tb_servico_adicional_cd_setor código ao suporte.',
        'fk_tb_relacionados_cd_pessoa_fisica_1' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_relacionados_cd_pessoa_fisica_1 ao suporte.',
        'fk_tb_relacionados_cd_pessoa_fisica_2' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_relacionados_cd_pessoa_fisica_2 ao suporte.',
        'fk_tb_pj_endereco_cd_pessoa_juridica' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pj_endereco_cd_pessoa_juridica ao suporte.',
        'fk_tb_pj_endereco_cd_catg_end' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pj_endereco_cd_catg_end ao suporte.',
        'fk_tb_pj_endereco_cd_catg_end_cd_vl_catg_end' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pj_endereco_cd_catg_end_cd_vl_catg_end ao suporte.',
        'fk_tb_pf_endereco_cd_pessoa_fisica' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pf_endereco_cd_pessoa_fisica ao suporte.',
        'fk_tb_pf_endereco_cd_catg_end_cd_vl_catg_end' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pf_endereco_cd_catg_end_cd_vl_catg_end ao suporte.',
        'fk_tb_pessoa_fisica_cd_pessoa_juridica' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pessoa_fisica_cd_pessoa_juridica ao suporte.',
        'fk_tb_pessoa_fisica_cd_profissao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pessoa_fisica_cd_profissao ao suporte.',
        'fk_tb_ordem_servico_cd_ocorrencia' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ordem_servico_cd_ocorrencia ao suporte.',
        'fk_tb_ordem_servico_cd_pf_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ordem_servico_cd_pf_executor ao suporte.',
        'fk_tb_ordem_servico_cd_pf_solicitante' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ordem_servico_cd_pf_solicitante ao suporte.',
        'fk_tb_orcamento_cd_ordem_servico' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_orcamento_cd_ordem_servico ao suporte.',
        'fk_tb_ocorrencia_cd_pf_informante' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_cd_pf_informante ao suporte.',
        'fk_tb_ocorrencia_pf_envolvida_cd_pessoa_fisica' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_pf_envolvida_cd_pessoa_fisica ao suporte.',
        'fk_tb_ocorrencia_pf_envolvida_cd_ocorrencia' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_pf_envolvida_cd_ocorrencia ao suporte.',
        'fk_tb_morador_endereco_cd_pessoa_fisica' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_morador_endereco_cd_pessoa_fisica ao suporte.',
        'fk_tb_morador_endereco_cd_apartamento' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_morador_endereco_cd_apartamento ao suporte.',
        'fk_tb_itens_orcamento_cd_pessoa_juridica' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_itens_orcamento_cd_pessoa_juridica ao suporte.',
        'fk_tb_itens_orcamento_cd_orcamento' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_itens_orcamento_cd_orcamento ao suporte.',
        'fk_tb_categoria_valor_cd_categoria' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_categoria_valor_cd_categoria ao suporte.',
        'fk_tb_apartamento_cd_setor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_apartamento_cd_setor ao suporte.',
        'fk_tb_condominio_cd_catg_estado_cd_catg_vl_estado' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_condominio_cd_catg_estado_cd_catg_vl_estado ao suporte.',
        'fk_tb_pf_endereco_cd_catg_estado_cd_catg_vl_estado' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pf_endereco_cd_catg_estado_cd_catg_vl_estado ao suporte.',
        'fk_tb_pj_endereco_cd_catg_estado_cd_catg_vl_estado' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pj_endereco_cd_catg_estado_cd_catg_vl_estado ao suporte.',
        'fk_tb_ocorrencia_cd_setor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_cd_setor ao suporte.',
        'fk_tb_usuario_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_usuario_cd_usuario_criacao ao suporte.',
        'fk_tb_usuario_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_usuario_cd_usuario_atualiza ao suporte.',
        'fk_tb_setor_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_setor_cd_usuario_criacao ao suporte.',
        'fk_tb_setor_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_setor_cd_usuario_atualiza ao suporte.',
        'fk_tb_servico_adicional_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_servico_adicional_cd_usuario_criacao ao suporte.',
        'fk_tb_servico_adicional_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_servico_adicional_cd_usuario_atualiza ao suporte.',
        'fk_tb_relacionados_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_servico_adicional_cd_usuario_atualiza ao suporte.',
        'fk_tb_relacionados_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_relacionados_cd_usuario_atualiza ao suporte.',
        'fk_tb_profissao_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_profissao_cd_usuario_criacao ao suporte.',
        'fk_tb_profissao_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_profissao_cd_usuario_atualiza ao suporte.',
        'fk_tb_pj_endereco_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pj_endereco_cd_usuario_criacao ao suporte.',
        'fk_tb_pj_endereco_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código ao suporte.',
        'fk_tb_pf_endereco_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pf_endereco_cd_usuario_criacao ao suporte.',
        'fk_tb_pf_endereco_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pf_endereco_cd_usuario_atualiza ao suporte.',
        'fk_tb_pessoa_juridica_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pessoa_juridica_cd_usuario_criacao ao suporte.',
        'fk_tb_pessoa_juridica_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pessoa_juridica_cd_usuario_atualiza ao suporte.',
        'fk_tb_pessoa_fisica_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pessoa_fisica_cd_usuario_criacao ao suporte.',
        'fk_tb_pessoa_fisica_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pessoa_fisica_cd_usuario_atualiza ao suporte.',
        'fk_tb_ordem_servico_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ordem_servico_cd_usuario_criacao ao suporte.',
        'fk_tb_ordem_servico_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ordem_servico_cd_usuario_atualiza ao suporte.',
        'fk_tb_orcamento_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_orcamento_cd_usuario_criacao ao suporte.',
        'fk_tb_orcamento_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_orcamento_cd_usuario_atualiza ao suporte.',
        'fk_tb_ocorrencia_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_cd_usuario_criacao ao suporte.',
        'fk_tb_ocorrencia_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_cd_usuario_atualiza ao suporte.',
        'fk_tb_ocorrencia_pf_envolvida_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_pf_envolvida_cd_usuario_criacao ao suporte.',
        'fk_tb_ocorrencia_pf_envolvida_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_pf_envolvida_cd_usuario_atualiza ao suporte.',
        'fk_tb_morador_endereco_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_morador_endereco_cd_usuario_criacao ao suporte.',
        'fk_tb_morador_endereco_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_morador_endereco_cd_usuario_atualiza ao suporte.',
        'fk_tb_itens_orcamento_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_itens_orcamento_cd_usuario_criacao ao suporte.',
        'fk_tb_itens_orcamento_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_itens_orcamento_cd_usuario_atualiza ao suporte.',
        'fk_tb_condominio_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_condominio_cd_usuario_criacao ao suporte.',
        'fk_tb_condominio_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_condominio_cd_usuario_atualiza ao suporte.',
        'fk_tb_categoria_valor_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_categoria_valor_cd_usuario_criacao ao suporte.',
        'fk_tb_categoria_valor_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_categoria_valor_cd_usuario_atualiza ao suporte.',
        'fk_tb_categoria_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_categoria_cd_usuario_criacao ao suporte.',
        'fk_tb_categoria_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_categoria_cd_usuario_atualiza ao suporte.',
        'fk_tb_apartamento_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_apartamento_cd_usuario_criacao ao suporte.',
        'fk_tb_apartamento_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_apartamento_cd_usuario_atualiza ao suporte.',
        'fk_tb_vaga_garagem_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_vaga_garagem_cd_usuario_criacao ao suporte.',
        'fk_tb_vaga_garagem_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_vaga_garagem_cd_usuario_atualiza ao suporte.',
        'fk_tb_pf_telefone_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pf_telefone_cd_usuario_criacao ao suporte.',
        'fk_tb_pf_telefone_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pf_telefone_cd_usuario_atualiza ao suporte.',
        'fk_tb_pj_telefone_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pj_telefone_cd_usuario_criacao ao suporte.',
        'fk_tb_pj_telefone_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pj_telefone_cd_usuario_atualiza ao suporte.',
        'fk_tb_instituicao_ensino_cd_usuario_criacao' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_instituicao_ensino_cd_usuario_criacao ao suporte.',
        'fk_tb_instituicao_ensino_cd_usuario_atualiza' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_instituicao_ensino_cd_usuario_atualiza ao suporte.',
        'pk_tb_apartamento_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_apartamento_log_nr_seq_log ao suporte.',
        'pk_tb_categoria_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_categoria_log_nr_seq_log ao suporte.',
        'pk_tb_categoria_valor_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_categoria_valor_log_nr_seq_log ao suporte.',
        'pk_tb_condominio_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_condominio_log_nr_seq_log ao suporte.',
        'pk_tb_itens_orcamento_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_itens_orcamento_log_nr_seq_log ao suporte.',
        'pk_tb_morador_endereco_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_morador_endereco_log_nr_seq_log ao suporte.',
        'pk_tb_cd_ocorrencia_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_cd_ocorrencia_log_nr_seq_log ao suporte.',
        'pk_tb_ocorrencia_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_ocorrencia_log_nr_seq_log ao suporte.',
        'pk_tb_orcamento_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_orcamento_log_nr_seq_log ao suporte.',
        'pk_tb_ordem_servico_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_ordem_servico_log_nr_seq_log ao suporte.',
        'pk_tb_pessao_fisica_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_pessao_fisica_log_nr_seq_log ao suporte.',
        'pk_tb_pessao_juridica_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_pessao_juridica_log_nr_seq_log ao suporte.',
        'pk_tb_pf_endereco_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_pf_endereco_log_nr_seq_log ao suporte.',
        'pk_tb_pj_endereco_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_pj_endereco_log_nr_seq_log ao suporte.',
        'pk_tb_profissao_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_profissao_log_nr_seq_log ao suporte.',
        'pk_tb_relacionados_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_relacionados_log_nr_seq_log ao suporte.',
        'pk_tb_servico_adicional_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_servico_adicional_log_nr_seq_log ao suporte.',
        'pk_tb_setor_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_setor_log_nr_seq_log ao suporte.',
        'pk_tb_usuario_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código ao pk_tb_usuario_log_nr_seq_log suporte.',
        'pk_tb_vaga_garagem_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_vaga_garagem_log_nr_seq_log ao suporte.',
        'pk_tb_pf_telefone_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_pf_telefone_nr_seq_log ao suporte.',
        'pk_tb_pj_telefon_log_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_pj_telefon_log_nr_seq_log ao suporte.',
        'pk_tb_instituicao_ensino_nr_seq_log' => 'Algo terrível aconteceu!! :-( Informe o código pk_tb_instituicao_ensino_nr_seq_log ao suporte.',
        'fk_tb_usuario_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_usuario_log_usu_executor ao suporte.',
        'fk_tb_setor_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_setor_log_usu_executor ao suporte.',
        'fk_tb_servico_adicional_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_servico_adicional_log_usu_executor ao suporte.',
        'fk_tb_relacionados_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_relacionados_log_usu_executor ao suporte.',
        'fk_tb_profissao_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_profissao_log_usu_executor ao suporte.',
        'fk_tb_pj_endereco_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pj_endereco_log_usu_executor ao suporte.',
        'fk_tb_pf_endereco_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código ao suporte.',
        'fk_tb_pessoa_juridica_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pf_endereco_log_usu_executor ao suporte.',
        'fk_tb_pessoa_fisica_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pessoa_fisica_log_usu_executor ao suporte.',
        'fk_tb_ordem_servico_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ordem_servico_log_usu_executor ao suporte.',
        'fk_tb_orcamento_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_orcamento_log_usu_executor ao suporte.',
        'fk_tb_ocorrencia_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_log_usu_executor ao suporte.',
        'fk_tb_ocorrencia_pf_envolvida_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_ocorrencia_pf_envolvida_log_usu_executor ao suporte.',
        'fk_tb_morador_endereco_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_morador_endereco_log_usu_executor ao suporte.',
        'fk_tb_itens_orcamento_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_itens_orcamento_log_usu_executor ao suporte.',
        'fk_tb_condominio_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_condominio_log_usu_executor ao suporte.',
        'fk_tb_categoria_valor_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_categoria_valor_log_usu_executor ao suporte.',
        'fk_tb_categoria_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_categoria_log_usu_executor ao suporte.',
        'fk_tb_apartamento_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_apartamento_log_usu_executor ao suporte.',
        'fk_tb_vaga_garagem_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_vaga_garagem_log_usu_executor ao suporte.',
        'fk_tb_pf_telefone_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pf_telefone_log_usu_executor ao suporte.',
        'fk_tb_pj_telefone_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_pj_telefone_log_usu_executor ao suporte.',
        'fk_tb_instituicao_ensino_log_usu_executor' => 'Algo terrível aconteceu!! :-( Informe o código fk_tb_instituicao_ensino_log_usu_executor ao suporte.',

    );

    public static function msg($mensagem)
    {
        foreach (self::$constraints as $constraint => $msg) {
            $mensagem = strpos($mensagem, $constraint) ? $msg : $mensagem;
        }

        return $mensagem;
    }
}