/* NOVAS TABELAS */
CREATE TABLE TB_INFO_ESTUDOS(
  CD_INFO_ESTUDOS SERIAL,
  CD_PESSOA_FISICA INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_PESSOA_FISICA NOT NULL, -- Quem
  CD_INSTITUICAO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_INSTITUICAO NOT NULL, -- Onde
  CD_CATG_CURSO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_CATG_CURSO NOT NULL, -- Cat Curso
  CD_VL_CATG_CURSO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_VL_CATG_CURSO NOT NULL, -- Qual Curso
  CD_CATG_PERIODO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_CATG_PERIODO NOT NULL, -- Cat Período
  CD_VL_CATG_PERIODO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_VL_CATG_PERIODO NOT NULL, -- Matutino, Noturno, Integral
  DT_INICIO DATE CONSTRAINT NN_TB_INFO_ESTUDOS_DT_INICIO NOT NULL, -- Início do Curso
  DT_FIM DATE CONSTRAINT NN_TB_INFO_ESTUDOS_DT_FIM NOT NULL, -- Previsão da Conclusão
  ----------------------------------------------------------------------------------------
  CD_USUARIO_CRIACAO INTEGER CONSTRAINT NN_TB_SETOR_CD_USUARIO_CRIACAO NOT NULL,
  DT_USUARIO_CRIACAO TIMESTAMP CONSTRAINT NN_TB_SETOR_DT_USUARIO_CRIACAO NOT NULL,
  CD_USUARIO_ATUALIZA INTEGER CONSTRAINT NN_TB_SETOR_CD_USUARIO_ATUALIZA NOT NULL,
  DT_USUARIO_ATUALIZA TIMESTAMP CONSTRAINT NN_TB_SETOR_DT_USUARIO_ATUALIZA NOT NULL,
  CONSTRAINT PK_TB_INFO_ESTUDOS_CD_INFO_ESTUDOS PRIMARY KEY(CD_INFO_ESTUDOS),
  CONSTRAINT UQ_TB_INFO_ESTUDOS
    UNIQUE (
      CD_PESSOA_FISICA,
      CD_INSTITUICAO,
      CD_VL_CATG_CURSO,
      CD_VL_CATG_PERIODO,
      DT_INICIO,
      DT_FIM
  )
);

-- CONSTRAINTS PARA TB_INFO_ESTUDOS

-- FOREIGN KEY PARA PESSOA FISICA
ALTER TABLE TB_INFO_ESTUDOS ADD CONSTRAINT FK_TB_INFO_ESTUDOS_CD_PESSOA_FISICA
  FOREIGN KEY(CD_PESSOA_FISICA) REFERENCES TB_PESSOA_FISICA(CD_PESSOA_FISICA);

-- FOREIGN KEY PARA PESSOA JURÍDICA
ALTER TABLE TB_INFO_ESTUDOS ADD CONSTRAINT FK_TB_INFO_ESTUDOS_CD_PESSOA_JURIDICA
  FOREIGN KEY(CD_PESSOA_JURIDICA) REFERENCES TB_PESSOA_JURIDICA(CD_PESSOA_JURIDICA);

-- FOREIGN KEY CATG CURSO
ALTER TABLE TB_INFO_ESTUDOS ADD CONSTRAINT FK_TB_INFO_ESTUDOS_CD_CATG_CURSO_CD_VL_CATG_CURSO
FOREIGN KEY(CD_CATG_CURSO,CD_VL_CATG_CURSO) REFERENCES TB_CATEGORIA_VALOR(CD_CATEGORIA,CD_VL_CATEGORIA);

-- FOREIGN KEY CATG PERÍODO
ALTER TABLE TB_INFO_ESTUDOS ADD CONSTRAINT FK_TB_INFO_ESTUDOS_CD_CATG_PERIODO_CD_VL_CATG_PERIODO
FOREIGN KEY(CD_CATG_PERIODO,CD_VL_CATG_PERIODO) REFERENCES TB_CATEGORIA_VALOR(CD_CATEGORIA,CD_VL_CATEGORIA);


CREATE TABLE TB_INFO_ESTUDOS_LOG(
  NR_SEQ_LOG INTEGER,
  USU_EXECUTOR INTEGER CONSTRAINT NN_TB_SETOR_LOG_USU_EXECUTOR NOT NULL,
  DT_EXECUTOR TIMESTAMP CONSTRAINT NN_TB_SETOR_LOG_DT_EXECUTOR NOT NULL,
  COMANDO_EXECUTADO CHAR(1) CONSTRAINT NN_TB_SETOR_LOG_COMANDO_EXECUTADO NOT NULL,
  -------------------------------------------------------------------------------
  CD_INFO_ESTUDOS SERIAL,
  CD_PESSOA_FISICA INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_PESSOA_FISICA NOT NULL, -- Quem
  CD_INSTITUICAO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_INSTITUICAO NOT NULL, -- Onde
  CD_CATG_CURSO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_CATG_CURSO NOT NULL, -- Cat Curso
  CD_VL_CATG_CURSO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_VL_CATG_CURSO NOT NULL, -- Qual Curso
  CD_CATG_PERIODO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_CATG_PERIODO NOT NULL, -- Cat Período
  CD_VL_CATG_PERIODO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_VL_CATG_PERIODO NOT NULL, -- Matutino, Noturno, Integral
  DT_INICIO DATE CONSTRAINT NN_TB_INFO_ESTUDOS_DT_INICIO NOT NULL, -- Início do Curso
  DT_FIM DATE CONSTRAINT NN_TB_INFO_ESTUDOS_DT_FIM NOT NULL, -- Previsão da Conclusão
  ----------------------------------------------------------------------------------------
  CD_USUARIO_CRIACAO INTEGER CONSTRAINT NN_TB_SETOR_CD_USUARIO_CRIACAO NOT NULL,
  DT_USUARIO_CRIACAO TIMESTAMP CONSTRAINT NN_TB_SETOR_DT_USUARIO_CRIACAO NOT NULL,
  CD_USUARIO_ATUALIZA INTEGER CONSTRAINT NN_TB_SETOR_CD_USUARIO_ATUALIZA NOT NULL,
  DT_USUARIO_ATUALIZA TIMESTAMP CONSTRAINT NN_TB_SETOR_DT_USUARIO_ATUALIZA NOT NULL,
  CONSTRAINT PK_TB_INFO_ESTUDOS_LOG_NR_SEQ_LOG PRIMARY KEY(NR_SEQ_LOG)
);








/* REFORMULAÇÃO DE TABELAS */
CREATE TABLE TB_PESSOA_FISICA(
  CD_PESSOA_FISICA SERIAL,
  CD_PESSOA_JURIDICA INTEGER,
  CD_PROFISSAO INTEGER,
  NM_PESSOA_FISICA VARCHAR(50) CONSTRAINT NN_TB_PESSOA_FISICA_NM_PESSOA_FISICA NOT NULL,
  CPF VARCHAR(14),
  RG VARCHAR(15),
  CD_CATG_ORG_RG INTEGER,
  CD_VL_CATG_ORG_RG INTEGER,
  EMAIL VARCHAR(60),
  DT_NASCIMENTO DATE,
  IE_SEXO CHAR(1) CONSTRAINT NN_TB_PESSOA_FISICA_IE_SEXO NOT NULL,
  IM_PERFIL OID,
--------------------------------------------------------
  CD_CIDADE_ORIGEM INTEGER,
--------------------------------------------------------
  CD_USUARIO_CRIACAO INTEGER,
  DT_USUARIO_CRIACAO TIMESTAMP,
  CD_USUARIO_ATUALIZA INTEGER,
  DT_USUARIO_ATUALIZA TIMESTAMP,
  CONSTRAINT PK_TB_PESSAO_FISICA_CD_PESSOA_FISICA PRIMARY KEY(CD_PESSOA_FISICA),
  CONSTRAINT UQ_TB_PESSOA_FISICA_CPF UNIQUE(CPF),
  CONSTRAINT UQ_TB_PESSOA_FISICA_RG UNIQUE(RG),
  CONSTRAINT UQ_TB_PESSOA_FISICA_EMAIL UNIQUE(EMAIL)
);
-- SOMENTE APÓS A CRIAÇÃO DA TABELA CIDADES E TABELA ESTADOS
ALTER TABLE TB_PESSOA_FISICA ADD CONSTRAINT FK_TB_PESSOA_FISICA_CD_CIDADE_ORIGEM
FOREIGN KEY(CD_CIDADE_ORIGEM) REFERENCES TB_CIDADES(ID);

CREATE TABLE TB_ORDEM_SERVICO(
  CD_ORDEM_SERVICO SERIAL,
  --------------------------------------------------------------
  CD_SETOR INTEGER,
  --------------------------------------------------------------
  CD_OCORRENCIA INTEGER,
  CD_PF_EXECUTOR INTEGER,
  CD_PF_SOLICITANTE INTEGER CONSTRAINT NN_TB_ORDEM_SERVICO_CD_PF_SOLICITANTE NOT NULL,
  DESC_ASSUNTO VARCHAR(50) CONSTRAINT NN_TB_ORDEM_SERVICO_DESC_ASSUNTO NOT NULL,
  DESC_ORDEM_SERVICO TEXT CONSTRAINT NN_TB_ORDEM_SERVICO_DESC_ORDEM_SERVICO NOT NULL,
  DT_INICIO TIMESTAMP CONSTRAINT NN_TB_ORDEM_SERVICO_DT_INICIO NOT NULL,
  DT_FIM TIMESTAMP,
  CD_CATG_ESTAGIO INTEGER CONSTRAINT NN_TB_ORDEM_SERVICO_CD_CATG_ESTAGIO NOT NULL,
  CD_VL_CATG_ESTAGIO INTEGER CONSTRAINT NN_TB_ORDEM_SERVICO_CD_VL_CATG_ESTAGIO NOT NULL,
  CD_CATG_AVAL_ATENDIMENTO INTEGER,
  CD_VL_CATG_AVAL_ATENDIMENTO INTEGER,
  CD_CATG_AVAL_QUALIDADE INTEGER,
  CD_VL_CATG_AVAL_QUALIDADE INTEGER,
  DESC_CONCLUSAO TEXT,
  --------------------------------------------------------------
  VALOR_MATERIAL NUMERIC(7,2),
  VALOR_SERVICO NUMERIC(7,2),
  --------------------------------------------------------------
  CD_CATG_TIPO INTEGER CONSTRAINT NN_TB_ORDEM_SERVICO_CD_CATG_TIPO NOT NULL,
  CD_VL_CATG_TIPO INTEGER CONSTRAINT NN_TB_ORDEM_SERVICO_CD_CATG_TIPO NOT NULL,
  --------------------------------------------------------------
  CD_CATG_SUB_TIPO INTEGER CONSTRAINT NN_TB_ORDEM_SERVICO_CD_CATG_SUB_TIPO NOT NULL,
  CD_VL_CATG_SUB_TIPO INTEGER CONSTRAINT NN_TB_ORDEM_SERVICO_CD_VL_CATG_SUB_TIPO NOT NULL,
  --------------------------------------------------------------
  CD_USUARIO_CRIACAO INTEGER CONSTRAINT NN_TB_ORDEM_SERVICO_CD_USUARIO_CRIACAO NOT NULL,
  DT_USUARIO_CRIACAO TIMESTAMP CONSTRAINT NN_TB_ORDEM_SERVICO_DT_USUARIO_CRIACAO NOT NULL,
  CD_USUARIO_ATUALIZA INTEGER CONSTRAINT NN_TB_ORDEM_SERVICO_CD_USUARIO_ATUALIZA NOT NULL,
  DT_USUARIO_ATUALIZA TIMESTAMP CONSTRAINT NN_TB_ORDEM_SERVICO_DT_USUARIO_ATUALIZA NOT NULL,
  CONSTRAINT PK_TB_ORDEM_SERVICO_TESTE_CD_ORDEM_SERVICO PRIMARY KEY(CD_ORDEM_SERVICO)
);

ALTER TABLE TB_ORDEM_SERVICO ADD CONSTRAINT FK_TB_ORDEM_SERVICO_CD_SETOR
  FOREIGN KEY(CD_SETOR) REFERENCES TB_SETOR(CD_SETOR);

ALTER TABLE tb_ordem_servico ADD CONSTRAINT fk_tb_ordem_servico_cd_catg_sub_tipo_cd_catg_vl_sub_tipo
FOREIGN KEY(cd_catg_sub_tipo,cd_vl_catg_sub_tipo) REFERENCES tb_categoria_valor(cd_categoria,cd_vl_categoria);


------------------------------------------------------------------------------------------
CREATE TABLE TB_SETOR(
  CD_SETOR SERIAL,
  CD_CONDOMINIO INTEGER CONSTRAINT NN_TB_SETOR_CD_CONDOMINIO NOT NULL,
  NM_SETOR VARCHAR(50) CONSTRAINT NN_TB_SETOR_NM_SETOR NOT NULL,
  -------------------------------
  CD_SETOR_GRUPO INTEGER,
  RAMAL VARCHAR(4),
  -------------------------------
  OBSERVACAO TEXT,
  IM_PERFIL OID,
  CD_CATG_TIPO INTEGER CONSTRAINT NN_TB_SETOR_CD_CATG_TIPO NOT NULL,
  CD_VL_CATG_TIPO INTEGER CONSTRAINT NN_TB_SETOR_CD_CATG_TIPO NOT NUll,
  -------------------------------
  CD_CATG_SUB_TIPO INTEGER CONSTRAINT NN_TB_SETOR_CD_CATG_SUB_TIPO NOT NULL,
  CD_VL_CATG_SUB_TIPO INTEGER CONSTRAINT NN_TB_SETOR_CD_CATG_SUB_TIPO NOT NUll,
  -------------------------------
  CD_USUARIO_CRIACAO INTEGER CONSTRAINT NN_TB_SETOR_CD_USUARIO_CRIACAO NOT NULL,
  DT_USUARIO_CRIACAO TIMESTAMP CONSTRAINT NN_TB_SETOR_DT_USUARIO_CRIACAO NOT NULL,
  CD_USUARIO_ATUALIZA INTEGER CONSTRAINT NN_TB_SETOR_CD_USUARIO_ATUALIZA NOT NULL,
  DT_USUARIO_ATUALIZA TIMESTAMP CONSTRAINT NN_TB_SETOR_DT_USUARIO_ATUALIZA NOT NULL,
  CONSTRAINT PK_TB_SETOR_CD_SETOR PRIMARY KEY(CD_SETOR),
  -------------------------------
  CONSTRAINT FK_TB_SETOR_CD_SETOR_GRUPO FOREIGN KEY(CD_SETOR_GRUPO)
    REFERENCES TB_SETOR(CD_SETOR)
  -------------------------------
);
