/* NOVAS TABELAS */
CREATE TABLE TB_INFO_ESTUDOS(
  CD_PESSOA_FISICA INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_PESSOA_FISICA NOT NULL, -- Quem
  CD_INSTITUICAO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_INSTITUICAO NOT NULL, -- Onde
  CD_CATG_CURSO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_CATG_CURSO NOT NULL, -- Cat Curso
  CD_VL_CATG_CURSO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_VL_CATG_CURSO NOT NULL, -- Qual Curso
  CD_CATG_TIPO_CURSO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_CATG_TIPO_CURSO NOT NULL, -- Cat Tipo Curso
  CD_VL_CATG_TIPO_CURSO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_VL_CATG_TIPO_CURSO NOT NULL, -- Exatas, Humanas, etc
  CD_CATG_PERIODO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_CATG_PERIODO NOT NULL, -- Cat Período
  CD_VL_CATG_PERIODO INTEGER CONSTRAINT NN_TB_INFO_ESTUDOS_CD_VL_CATG_PERIODO NOT NULL, -- Matutino, Noturno, Integral
  DT_INICIO TIMESTAMP CONSTRAINT NN_TB_INFO_ESTUDOS_DT_INICIO NOT NULL, -- Início do Curso
  DT_FIM TIMESTAMP CONSTRAINT NN_TB_INFO_ESTUDOS_DT_FIM NOT NULL, -- Previsão da Conclusão
-------------------------------------------------------------------------------------------------------------
  CD_USUARIO_CRIACAO INTEGER CONSTRAINT NN_TB_SETOR_CD_USUARIO_CRIACAO NOT NULL,
  DT_USUARIO_CRIACAO TIMESTAMP CONSTRAINT NN_TB_SETOR_DT_USUARIO_CRIACAO NOT NULL,
  CD_USUARIO_ATUALIZA INTEGER CONSTRAINT NN_TB_SETOR_CD_USUARIO_ATUALIZA NOT NULL,
  DT_USUARIO_ATUALIZA TIMESTAMP CONSTRAINT NN_TB_SETOR_DT_USUARIO_ATUALIZA NOT NULL
);

CREATE TABLE TB_SUB_SETOR(
  CD_SUB_SETOR SERIAL,
  CD_SETOR INTEGER CONSTRAINT NN_TB_SUB_SETOR_CD_SETOR NOT NULL,
  DESC_SUB_SETOR VARCHAR(10) CONSTRAINT NN_TB_SUB_SETOR_DESC_APARTAMENTO NOT NULL,
  CD_CATG_TIPO INTEGER CONSTRAINT NN_TBSUB_SETOR_CD_CATG_TIPO NOT NULL,
  CD_VL_CATG_TIPO INTEGER CONSTRAINT NN_TB_SUB_SETOR_CD_CATG_TIPO NOT NUll,
  CD_USUARIO_CRIACAO INTEGER CONSTRAINT NN_TB_SUB_SETOR_CD_USUARIO_CRIACAO NOT NULL,
  DT_USUARIO_CRIACAO TIMESTAMP CONSTRAINT NN_TB_SUB_SETOR_DT_USUARIO_CRIACAO NOT NULL,
  CD_USUARIO_ATUALIZA INTEGER CONSTRAINT NN_TB_SUB_SETOR_CD_USUARIO_ATUALIZA NOT NULL,
  DT_USUARIO_ATUALIZA TIMESTAMP CONSTRAINT NN_TB_SUB_SETOR_DT_USUARIO_ATUALIZA NOT NULL,
  CONSTRAINT PK_TB_SUB_SETOR_CD_SUB_SETOR PRIMARY KEY(CD_SUB_SETOR)
);

/* REFORMULAÇÃO DE TABELAS */
CREATE TABLE TB_PESSOA_FISICA(
  CD_PESSOA_FISICA SERIAL,
  CD_PESSOA_JURIDICA INTEGER,
  CD_PROFISSAO INTEGER,
  NM_PESSOA_FISICA VARCHAR(50) CONSTRAINT NN_TB_PESSOA_FISICA_NM_PESSOA_FISICA NOT NULL,
  CPF VARCHAR(14),
  RG VARCHAR(15),
  CD_CATG_ORG_RG INTEGER,
  CD_VL_CATG_ORG_RG INTEGER,
  EMAIL VARCHAR(60),
  DT_NASCIMENTO DATE,
  IE_SEXO CHAR(1) CONSTRAINT NN_TB_PESSOA_FISICA_IE_SEXO NOT NULL,
  IM_PERFIL OID,
  IE_ESTUDA CHAR(1),
  CD_CIDADE_ORIGEM INTEGER,
/*  Esses dados virão da TB_INFO_ESTUDOS
  CD_INSTITUICAO INTEGER,
  DT_INICIO_CURSO DATE,
  DT_FIM_CURSO DATE,
  CD_CATG_GRAU_ENSINO INTEGER,
  CD_VL_CATG_GRAU_ENSINO INTEGER,*/
  CD_USUARIO_CRIACAO INTEGER,
  DT_USUARIO_CRIACAO TIMESTAMP,
  CD_USUARIO_ATUALIZA INTEGER,
  DT_USUARIO_ATUALIZA TIMESTAMP,
  CONSTRAINT PK_TB_PESSAO_FISICA_CD_PESSOA_FISICA PRIMARY KEY(CD_PESSOA_FISICA),
  CONSTRAINT UQ_TB_PESSOA_FISICA_CPF UNIQUE(CPF),
  CONSTRAINT UQ_TB_PESSOA_FISICA_RG UNIQUE(RG),
  CONSTRAINT UQ_TB_PESSOA_FISICA_EMAIL UNIQUE(EMAIL)
);
-- SOMENTE APÓS A CRIAÇÃO DA TABELA CIDADES E TABELA ESTADOS
ALTER TABLE TB_PESSOA_FISICA ADD CONSTRAINT FK_TB_PESSOA_FISICA_CD_CIDADE_ORIGEM
FOREIGN KEY(CD_CIDADE_ORIGEM) REFERENCES CIDADES(ID);