
----------------------------- Criar o Banco -----------------------------

CREATE DATABASE DNACRM
TEMPLATE TEMPLATE0
ENCODING 'UTF-8'
CONNECTION LIMIT 40;

/*

Instrções

 Apos criarem o banco com o comando acima, vão sair e entrar do pgAdmin, ir no banco SISCON e executar os comandos abaixo ou conectar na sessao do banco SISCON e excutar os comandos.


*/



----------------------------- Tabelas do Banco -----------------------------

CREATE TABLE APARTAMENTO_TB (
  CD_APARTAMENTO SERIAL CONSTRAINT NN_APARTAMENTO_CD_APARTAMENTO NOT NULL,
  CD_PREDIO INTEGER CONSTRAINT NN_APARTAMENTO_CD_PREDIO NOT NULL,
  DESC_APARTAMENTO VARCHAR(10),
  CONSTRAINT PK_APARTAMENTO_CD_APARTAMENTO PRIMARY KEY(CD_APARTAMENTO)
);

CREATE TABLE CATEGORIA_TB (
  CD_CATEGORIA SERIAL CONSTRAINT NN_CATEGORIA_CD_CATEGORIA NOT NULL,
  DESC_CATEGORIA VARCHAR(50),
  CONSTRAINT PK_CATEGORIA_CD_CATEGORIA PRIMARY KEY(CD_CATEGORIA)
);

CREATE TABLE CATEGORIA_VALOR_TB  (
  CD_VL_CATEGORIA SERIAL CONSTRAINT NN_CD_VL_CATEGORIA NOT NULL,
  CD_CATEGORIA INTEGER CONSTRAINT NN_CATEGORIA_CD_CATEGORIA NOT NULL,
  DESC_VL_CATG VARCHAR(25),
  CONSTRAINT PK_CD_VL_CATEGORIA_CD_CATEGORIA PRIMARY KEY(CD_VL_CATEGORIA, CD_CATEGORIA)
);

CREATE TABLE CONDOMINIO_TB (
  CD_CONDOMINIO SERIAL CONSTRAINT NN_CONDOMINIO_CD_CONDOMINIO NOT NULL,
  NM_CONDOMINIO VARCHAR(50),
  CEP NUMERIC(8,0),
  RUA VARCHAR(50),
  NUMERO INTEGER,
  BAIRRO VARCHAR(50),
  CIDADE VARCHAR(25),
  ESTADO VARCHAR(25),
  CONSTRAINT PK_CONDOMINIO_CD_CONDOMINIO PRIMARY KEY(CD_CONDOMINIO)
);

CREATE TABLE ITENS_ORCAMENTO_TB (
  NR_SEQUENCIA SERIAL CONSTRAINT NN_INTES_ORACAMENTO_NR_SEQUENCIA NOT NULL,
  CD_ORCAMENTO INTEGER CONSTRAINT NN_INTES_ORACAMENTO_CD_ORCAMENTO NOT NULL,
  CD_CGC INTEGER NOT NULL,
  DESC_ITEM VARCHAR(50),
  QT_ITEM INTEGER,
  VALOR_UNIT NUMERIC(10,2),
  VALOR_TOTAL NUMERIC(10,2),
  IE_APROVADO CHAR(1),
  CONSTRAINT PK_ITENS_ORCAMENTO_NR_SEQ PRIMARY KEY(NR_SEQUENCIA)
);

CREATE TABLE MORADOR_ENDERECO_TB (
  NR_SEQUENCIA SERIAL CONSTRAINT NN_MORADOR_ENDERECO_NR_SEQUENCIA NOT NULL,
  CD_PESSOA_FISICA INTEGER CONSTRAINT NN_MORADOR_ENDERECO_CD_PF NOT NULL,
  CD_APARTAMENTO INTEGER CONSTRAINT NN_MORADOR_ENDERECP_CD_AP NOT NULL,
  DT_ENTRADA DATE,
  DT_SAIDA DATE,
  CONSTRAINT PK_MORADOR_ENDERECO_NR_SEQ PRIMARY KEY(NR_SEQUENCIA)
);

CREATE TABLE OCORRENCIA_PF_ENVOLVIDA_TB (
  CD_OCORRENCIA INTEGER CONSTRAINT NN_OCORRENCIA_PF_ENVOLVIDA_CD_OC NOT NULL,
  CD_PESSOA_FISICA INTEGER CONSTRAINT NN_OCORRENCIA_PF_ENVOLVIDA_CD_PF NOT NULL,
  CONSTRAINT PK_CD_OCORRENCIA_CD_PF PRIMARY KEY(CD_OCORRENCIA, CD_PESSOA_FISICA)
);

CREATE TABLE OCORRENCIA_TB (
  CD_OCORRENCIA SERIAL CONSTRAINT NN_OCORRENCIA_CD_OC NOT NULL,
  CD_PF_INFORMANTE INTEGER CONSTRAINT NN_OCORRENCIA_CD_PF_INFORMANTE NOT NULL,
  DESC_ASSUNTO VARCHAR(50),
  DESC_OCORRENCIA TEXT,
  DT_OCORRENCIA DATE,
  IE_SITUACAO CHAR(1),
  DESC_CONCLUSAO TEXT,
  CONSTRAINT PK_OCORRENCIA_CD_OCORRENICA PRIMARY KEY(CD_OCORRENCIA)
);

CREATE TABLE ORCAMENTO_TB (
  CD_ORCAMENTO SERIAL CONSTRAINT NN_ORCAMENTO_CD_OC NOT NULL,
  CD_ORDEM_SERVICO INTEGER CONSTRAINT NN_ORCAMENTO_OS NOT NULL,
  DT_ORCAMENTO DATE,
  CONSTRAINT PK_ORCAMENTO_CD_ORCAMENTO PRIMARY KEY(CD_ORCAMENTO)
);

CREATE TABLE ORDEM_SERVICO_TB (
  CD_ORDEM_SERVICO SERIAL CONSTRAINT NN_ORDEM_SERVICO_CD_OS NOT NULL,
  CD_OCORRENCIA INTEGER CONSTRAINT NN_ORDEM_sERVICO_CD_OC NOT NULL,
  CD_PF_EXECUTOR INTEGER CONSTRAINT NN_ORDEM_SERVICO_CD_PF_EXECUTOR NOT NULL,
  CD_PF_SOLICITANTE INTEGER CONSTRAINT NN_ORDEM_SERVICO_CD_PF_SOLICITANTE NOT NULL,
  DESC_ASSUNTO VARCHAR(50),
  DESC_ORDEM_SERVICO TEXT,
  DT_INICIO DATE,
  DT_FIM DATE,
  CONSTRAINT PK_ORDEM_SERVICO_CD_OS PRIMARY KEY(CD_ORDEM_SERVICO)
);

CREATE TABLE PESSOA_FISICA_TB (
  CD_PESSOA_FISICA SERIAL CONSTRAINT NN_PESSAO_FISICA_CD_PF NOT NULL,
  CD_CGC INTEGER,
  CD_PROFISSAO INTEGER,
  NM_PESSOA_FISICA VARCHAR(50),
  CPF NUMERIC(11,0),
  RG VARCHAR(15),
  ORG_RG CHAR(2),
  EMAIL VARCHAR(30),
  DDD_FONE NUMERIC(2,0),
  FONE NUMERIC(8,0),
  DDD_CELULAR NUMERIC(2,0),
  CELULAR NUMERIC(9,0),
  DT_NASCIMENTO DATE,
  IE_SEXO CHAR(1),
  DS_FOTO VARCHAR(50),
  IM_FOTO OID,
  CONSTRAINT PK_PESSAO_FISICA_CD_PF PRIMARY KEY(CD_PESSOA_FISICA)
);

CREATE TABLE PESSOA_JURIDICA_TB (
  CD_CGC SERIAL CONSTRAINT NN_PESSAO_JURIDICA_CD_CGC NOT NULL,
  NM_FANTASIA VARCHAR(50),
  DESC_RAZAO VARCHAR(50),
  DESC_ATIVIDADE TEXT,
  EMAIL VARCHAR(30),
  DDD_FONE NUMERIC(2,0),
  FONE NUMERIC(8,0),
  DDD_FAX NUMERIC(2,0),
  FONE_FAX NUMERIC(8,0),
  CONSTRAINT PK_PESSAO_JURIDICA_CD_CGC PRIMARY KEY(CD_CGC)
);

CREATE TABLE PF_ENDERECO_TB (
  NR_SEQUENCIA SERIAL CONSTRAINT NN_PF_ENDERECO_NR_SEQ NOT NULL,
  CD_CATG_END INTEGER CONSTRAINT NN_PF_ENDERECO_CD_CATG_END NOT NULL,
  CD_VL_CATG_END INTEGER CONSTRAINT NN_PF_ENDERECO_CD_VL_CATG_END NOT NULL,
  CD_PESSOA_FISICA INTEGER CONSTRAINT NN_PF_ENDERECO_CD_PF NOT NULL,
  CEP NUMERIC(8,0),
  RUA VARCHAR(50),
  NUMERO INTEGER,
  BAIRRO VARCHAR(25),
  CIDADE VARCHAR(25),
  ESTADO VARCHAR(25),
  CONSTRAINT PK_PF_ENDERECO_CD_PF PRIMARY KEY(NR_SEQUENCIA)
);

CREATE TABLE PJ_ENDERECO_TB (
  NR_SEQUENCIA SERIAL CONSTRAINT NN_PJ_ENDERECO_NR_SEQ NOT NULL,
  CD_CATG_END INTEGER CONSTRAINT NN_PJ_ENDERECO_CD_CATG_END NOT NULL,
  CD_VL_CATG_END INTEGER CONSTRAINT NN_PJ_ENDERECO_CD_VL_CATG_END NOT NULL,
  CD_CGC INTEGER CONSTRAINT NN_PJ_ENDERECO_CD_CGC NOT NULL,
  CEP NUMERIC(8,0),
  RUA VARCHAR(50),
  NUMERO INTEGER,
  BAIRRO VARCHAR(25),
  CIDADE VARCHAR(25),
  ESTADO VARCHAR(25),
  CONSTRAINT PK_PJ_ENDERECO_CD_CGC PRIMARY KEY(NR_SEQUENCIA)
);

CREATE TABLE PREDIO_TB (
  CD_PREDIO SERIAL NOT NULL,
  CD_SETOR INTEGER NOT NULL,
  DESC_PREDIO VARCHAR(10),
  CONSTRAINT PK_PREDIO_CD_PREDIO PRIMARY KEY(CD_PREDIO)
);

CREATE TABLE PROFISSAO_TB (
  CD_PROFISSAO SERIAL CONSTRAINT NN_PROFISSAO_CD_PROFISSAO NOT NULL,
  NM_PROFISSAO VARCHAR(50),
  CONSTRAINT PK_PROFISSAO_CD_PROFISSAO PRIMARY KEY(CD_PROFISSAO)
);

CREATE TABLE RELACIONADOS_TB (
  CD_PESSOA_FISICA_1 INTEGER CONSTRAINT NN_RELACIONADOS_CD_PF1 NOT NULL,
  CD_PESSOA_FISICA_2 INTEGER CONSTRAINT NN_RELACIONADOS_CD_PF2 NOT NULL,
  CD_CATG_RELAC INTEGER CONSTRAINT NN_RELACIONADOS_CD_CATG_RELAC NOT NULL,
  CD_VL_CATG_RELAC INTEGER CONSTRAINT NNN_RELACIONADOS_CD_VL_CATG_RELAC NOT NULL,
  CONSTRAINT PK_CD_PF1_CD_PF2  PRIMARY KEY(CD_PESSOA_FISICA_1, CD_PESSOA_FISICA_2)
);

CREATE TABLE SERVICO_ADICIONAL_TB (
  CD_SERV_ADICIONAL SERIAL CONSTRAINT NN_SERVICO_ADICIONAL_CD_SA NOT NULL,
  CD_ORDEM_SERVICO INTEGER CONSTRAINT NN_SERVICO_ADICIONAL_CD_OS NOT NULL,
  DT_INICIO DATE,
  DT_FIM INTEGER,
  CONSTRAINT PK_SERVICO_ADICIONAL_CD_SERV_ADICIONAL PRIMARY KEY(CD_SERV_ADICIONAL)
);

CREATE TABLE SETOR_TB (
  CD_SETOR SERIAL CONSTRAINT NN_SETOR_CD_SETOR NOT NULL,
  CD_CONDOMINIO INTEGER CONSTRAINT NN_SETOR_CD_CONDOMINIO NOT NULL,
  NM_SETOR VARCHAR(50),
  OBSERVACAO TEXT,
  CONSTRAINT PK_SETOR_CD_SETOR PRIMARY KEY(CD_SETOR)
);

CREATE TABLE USUARIO_TB (
  CD_USUARIO SERIAL CONSTRAINT NN_USUARIO_CD_USU NOT NULL,
  CD_PESSOA_FISICA INTEGER CONSTRAINT NN_USUARIO_CD_PF NOT NULL,
  CD_USUARIO_HABILITA INTEGER CONSTRAINT NN_USUARIO_CD_USU_HABILITA NOT NULL,
  LOGIN VARCHAR(20) NULL,
  SENHA VARCHAR(100) NULL,
  NIVEL INTEGER NOT NULL,
  IE_STATUS CHAR(1) NULL,
  CONSTRAINT PK_USUARIO_CD_USU PRIMARY KEY(CD_USUARIO)
);

ALTER TABLE USUARIO_TB ADD CONSTRAINT PF_FK_USUARIO FOREIGN KEY(CD_PESSOA_FISICA) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE USUARIO_TB ADD CONSTRAINT USU_FK_USUARIO FOREIGN KEY(CD_USUARIO_HABILITA) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE SETOR_TB ADD CONSTRAINT CONDOMINIO_FK_SETOR FOREIGN KEY(CD_CONDOMINIO) REFERENCES CONDOMINIO_TB(CD_CONDOMINIO);

ALTER TABLE SERVICO_ADICIONAL_TB ADD CONSTRAINT OS_FK_SERVICOADD FOREIGN KEY(CD_ORDEM_SERVICO) REFERENCES ORDEM_SERVICO_TB(CD_ORDEM_SERVICO);

ALTER TABLE RELACIONADOS_TB ADD CONSTRAINT PF1_FK_RELACIONADOS FOREIGN KEY(CD_PESSOA_FISICA_1) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE RELACIONADOS_TB ADD CONSTRAINT PF2_FK_RELACIONADOS FOREIGN KEY(CD_PESSOA_FISICA_2) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE PREDIO_TB ADD CONSTRAINT SETOR_FK_PREDIO FOREIGN KEY(CD_SETOR) REFERENCES SETOR_TB(CD_SETOR);

ALTER TABLE PJ_ENDERECO_TB ADD CONSTRAINT PJ_FK_PJEND FOREIGN KEY(CD_CGC) REFERENCES PESSOA_JURIDICA_TB(CD_CGC);

ALTER TABLE PJ_ENDERECO_TB ADD CONSTRAINT CATG_DM_FK_PJEND FOREIGN KEY(CD_CATG_END) REFERENCES CATEGORIA_TB(CD_CATEGORIA);

ALTER TABLE PJ_ENDERECO_TB ADD CONSTRAINT CATG_VL_FK_PJEND FOREIGN KEY(CD_CATG_END,CD_VL_CATG_END) REFERENCES CATEGORIA_VALOR_TB(CD_CATEGORIA,CD_VL_CATEGORIA);

ALTER TABLE PF_ENDERECO_TB ADD CONSTRAINT PF_FK_PFEND FOREIGN KEY(CD_PESSOA_FISICA) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE PF_ENDERECO_TB ADD CONSTRAINT CATG_VL_FK_PFEND FOREIGN KEY(CD_CATG_END,CD_VL_CATG_END) REFERENCES CATEGORIA_VALOR_TB(CD_CATEGORIA,CD_VL_CATEGORIA);

ALTER TABLE PESSOA_FISICA_TB ADD CONSTRAINT PJ_FK_PF FOREIGN KEY(CD_CGC) REFERENCES PESSOA_JURIDICA_TB(CD_CGC);

ALTER TABLE PESSOA_FISICA_TB ADD CONSTRAINT PROFISSAO_FK_PF FOREIGN KEY(CD_PROFISSAO) REFERENCES PROFISSAO_TB(CD_PROFISSAO);

ALTER TABLE ORDEM_SERVICO_TB ADD CONSTRAINT OCORRENCIA_FK_OS FOREIGN KEY(CD_OCORRENCIA) REFERENCES OCORRENCIA_TB(CD_OCORRENCIA);

ALTER TABLE ORDEM_SERVICO_TB ADD CONSTRAINT PF_EXE_FK_OS FOREIGN KEY(CD_PF_EXECUTOR) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE ORDEM_SERVICO_TB ADD CONSTRAINT PF_SOLC_FK_OS FOREIGN KEY(CD_PF_SOLICITANTE) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE ORCAMENTO_TB ADD CONSTRAINT OS_FK_ORCAMENTO FOREIGN KEY(CD_ORDEM_SERVICO) REFERENCES ORDEM_SERVICO_TB(CD_ORDEM_SERVICO);

ALTER TABLE OCORRENCIA_TB ADD CONSTRAINT PF_FK_OCORRENCIA FOREIGN KEY(CD_PF_INFORMANTE) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE OCORRENCIA_PF_ENVOLVIDA_TB ADD CONSTRAINT PF_FK_OCORRE_PF_ENVOL FOREIGN KEY (CD_PESSOA_FISICA) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE OCORRENCIA_PF_ENVOLVIDA_TB ADD CONSTRAINT OCORRENCIA_FK_OCORRE_PF_ENVOL FOREIGN KEY (CD_OCORRENCIA) REFERENCES OCORRENCIA_TB(CD_OCORRENCIA);

ALTER TABLE MORADOR_ENDERECO_TB ADD CONSTRAINT PF_FK_MORADOR FOREIGN KEY (CD_PESSOA_FISICA) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE MORADOR_ENDERECO_TB ADD CONSTRAINT APARTAMENTO_FK_MORADOR FOREIGN KEY (CD_APARTAMENTO) REFERENCES APARTAMENTO_TB(CD_APARTAMENTO);

ALTER TABLE ITENS_ORCAMENTO_TB ADD CONSTRAINT PJ_FK_ITENS FOREIGN KEY (CD_CGC) REFERENCES PESSOA_JURIDICA_TB(CD_CGC);

ALTER TABLE ITENS_ORCAMENTO_TB ADD CONSTRAINT ORCAMENTO_FK_ITENS FOREIGN KEY (CD_ORCAMENTO) REFERENCES ORCAMENTO_TB(CD_ORCAMENTO);

ALTER TABLE CATEGORIA_VALOR_TB ADD CONSTRAINT CATG_DM_FK_CATG_VL FOREIGN KEY (CD_CATEGORIA) REFERENCES CATEGORIA_TB(CD_CATEGORIA);

ALTER TABLE APARTAMENTO_TB ADD CONSTRAINT PREDIO_FK_APARTAMENTO FOREIGN KEY (CD_PREDIO) REFERENCES PREDIO_TB(CD_PREDIO);