CREATE DATABASE SiSCON;

/*

Instrções

 Apos criarem o banco com o comando acima, vão sair e entrar do pgAdmin, ir no banco SISCON e executar os comandos abaixo ou conectar na sessao do banco SISCON e excutar os comandos.


*/



----------------------------- Tabelas do Banco -----------------------------

CREATE TABLE APARTAMENTO_TB (
  CD_APARTAMENTO SERIAL NOT NULL,
  CD_PREDIO INTEGER NOT NULL,
  DESC_APARTAMENTO VARCHAR(10) NULL,
  PRIMARY KEY(CD_APARTAMENTO)
);

CREATE TABLE CATEGORIA_TB (
  CD_CATEGORIA SERIAL NOT NULL,
  DESC_CATEGORIA VARCHAR(50) NULL,
  PRIMARY KEY(CD_CATEGORIA)
);

CREATE TABLE CATEGORIA_VALOR_TB  (
  CD_VL_CATEGORIA SERIAL NOT NULL,
  CD_CATEGORIA INTEGER NOT NULL,
  DESC_VL_CATG VARCHAR(25) NULL,
  PRIMARY KEY(CD_VL_CATEGORIA, CD_CATEGORIA)
);

CREATE TABLE CONDOMINIO_TB (
  CD_CONDOMINIO SERIAL NOT NULL,
  NM_CONDOMINIO VARCHAR(50) NULL,
  CEP NUMERIC(8,0) NULL,
  RUA VARCHAR(50) NULL,
  NUMERO INTEGER NULL,
  BAIRRO VARCHAR(50) NULL,
  CIDADE VARCHAR(25) NULL,
  ESTADO VARCHAR(25) NULL,
  PRIMARY KEY(CD_CONDOMINIO)
);

CREATE TABLE ITENS_ORCAMENTO_TB (
  NR_SEQUENCIA SERIAL NOT NULL,
  CD_ORCAMENTO INTEGER NOT NULL,
  CD_CGC INTEGER NOT NULL,
  DESC_ITEM VARCHAR(50) NULL,
  QT_ITEM INTEGER NULL,
  VALOR_UNIT NUMERIC(10,2) NULL,
  VALOR_TOTAL NUMERIC(10,2) NULL,
  IE_APROVADO CHAR(1) NULL,
  PRIMARY KEY(NR_SEQUENCIA)
);

CREATE TABLE MORADOR_ENDERECO_TB (
  NR_SEQUENCIA SERIAL NOT NULL,
  CD_PESSOA_FISICA INTEGER NOT NULL,
  CD_APARTAMENTO INTEGER NOT NULL,
  DT_ENTRADA DATE NULL,
  DT_SAIDA DATE NULL,
  PRIMARY KEY(NR_SEQUENCIA)
);

CREATE TABLE OCORRENCIA_PF_ENVOLVIDA_TB (
  CD_OCORRENCIA INTEGER NOT NULL,
  CD_PESSOA_FISICA INTEGER NOT NULL,
  PRIMARY KEY(CD_OCORRENCIA, CD_PESSOA_FISICA)
);

CREATE TABLE OCORRENCIA_TB (
  CD_OCORRENCIA SERIAL NOT NULL,
  CD_PF_INFORMANTE INTEGER NOT NULL,
  DESC_ASSUNTO VARCHAR(50) NULL,
  DESC_OCORRENCIA TEXT NULL,
  DT_OCORRENCIA DATE NULL,
  IE_SITUACAO CHAR(1) NULL,
  DESC_CONCLUSAO TEXT NULL,
  PRIMARY KEY(CD_OCORRENCIA)
);

CREATE TABLE ORCAMENTO_TB (
  CD_ORCAMENTO SERIAL NOT NULL,
  CD_ORDEM_SERVICO INTEGER NOT NULL,
  DT_ORCAMENTO DATE NULL,
  PRIMARY KEY(CD_ORCAMENTO)
);

CREATE TABLE ORDEM_SERVICO_TB (
  CD_ORDEM_SERVICO SERIAL NOT NULL,
  CD_OCORRENCIA INTEGER NOT NULL,
  CD_PF_EXECUTOR INTEGER NOT NULL,
  CD_PF_SOLICITANTE INTEGER NOT NULL,
  DESC_ASSUNTO VARCHAR(50) NULL,
  DESC_ORDEM_SERVICO TEXT NULL,
  DT_INICIO DATE NULL,
  DT_FIM DATE NULL,
  PRIMARY KEY(CD_ORDEM_SERVICO)
);

CREATE TABLE PESSOA_FISICA_TB (
  CD_PESSOA_FISICA SERIAL NOT NULL,
  CD_CGC INTEGER NOT NULL,
  CD_PROFISSAO INTEGER NOT NULL,
  NM_PESSOA_FISICA VARCHAR(50) NULL,
  CPF NUMERIC(11,0) NULL,
  RG VARCHAR(15) NULL,
  ORG_RG CHAR(2) NULL,
  EMAIL VARCHAR(30) NULL,
  DDD_FONE NUMERIC(2,0) NULL,
  FONE NUMERIC(8,0) NULL,
  DDD_CELULAR NUMERIC(2,0) NULL,
  CELULAR NUMERIC(9,0) NULL,
  DT_NASCIMENTO DATE NULL,
  IE_SEXO CHAR(1) NULL,
  IM_FOTO OID NULL,
  PRIMARY KEY(CD_PESSOA_FISICA)
);

CREATE TABLE PESSOA_JURIDICA_TB (
  CD_CGC SERIAL NOT NULL,
  NM_FANTASIA VARCHAR(50) NULL,
  DESC_RAZAO VARCHAR(50) NULL,
  DESC_ATIVIDADE TEXT NULL,
  EMAIL VARCHAR(30) NULL,
  DDD_FONE NUMERIC(2,0) NULL,
  FONE NUMERIC(8,0) NULL,
  DDD_FAX NUMERIC(2,0) NULL,
  FONE_FAX NUMERIC(8,0) NULL,
  PRIMARY KEY(CD_CGC)
);

CREATE TABLE PF_ENDERECO_TB (
  NR_SEQUENCIA SERIAL NOT NULL,
  CD_CATG_END INTEGER NOT NULL,
  CD_VL_CATG_END INTEGER NOT NULL,
  CD_PESSOA_FISICA INTEGER NOT NULL,
  CEP NUMERIC(8,0) NULL,
  RUA VARCHAR(50) NULL,
  NUMERO INTEGER NULL,
  BAIRRO VARCHAR(25) NULL,
  CIDADE VARCHAR(25) NULL,
  ESTADO VARCHAR(25) NULL,
  PRIMARY KEY(NR_SEQUENCIA)
);

CREATE TABLE PJ_ENDERECO_TB (
  NR_SEQUENCIA SERIAL NOT NULL,
  CD_CATG_END INTEGER NOT NULL,
  CD_VL_CATG_END INTEGER NOT NULL,
  CD_CGC INTEGER NOT NULL,
  CEP NUMERIC(8,0) NULL,
  RUA VARCHAR(50) NULL,
  NUMERO INTEGER NULL,
  BAIRRO VARCHAR(25) NULL,
  CIDADE VARCHAR(25) NULL,
  ESTADO VARCHAR(25) NULL,
  PRIMARY KEY(NR_SEQUENCIA)
);

CREATE TABLE PREDIO_TB (
  CD_PREDIO SERIAL NOT NULL,
  CD_SETOR INTEGER NOT NULL,
  DESC_PREDIO VARCHAR(10) NULL,
  PRIMARY KEY(CD_PREDIO)
);

CREATE TABLE PROFISSAO_TB (
  CD_PROFISSAO SERIAL NOT NULL,
  NM_PROFISSAO VARCHAR(50) NULL,
  PRIMARY KEY(CD_PROFISSAO)
);

CREATE TABLE RELACIONADOS_TB (
  CD_PESSOA_FISICA_2 INTEGER NOT NULL,
  CD_PESSOA_FISICA_1 INTEGER NOT NULL,
  CD_CATG_RELAC INTEGER NOT NULL,
  CD_VL_CATG_RELAC INTEGER NOT NULL,
  PRIMARY KEY(CD_PESSOA_FISICA_2, CD_PESSOA_FISICA_1)
);

CREATE TABLE SERVICO_ADICIONAL_TB (
  CD_SERV_ADICIONAL SERIAL NOT NULL,
  CD_ORDEM_SERVICO INTEGER NOT NULL,
  DT_INICIO DATE NULL,
  DT_FIM INTEGER NULL,
  PRIMARY KEY(CD_SERV_ADICIONAL)
);

CREATE TABLE SETOR_TB (
  CD_SETOR SERIAL NOT NULL,
  CD_CONDOMINIO INTEGER NOT NULL,
  NM_SETOR VARCHAR(50) NULL,
  OBSERVACAO TEXT NULL,
  PRIMARY KEY(CD_SETOR)
);

CREATE TABLE USUARIO_TB (
  CD_USUARIO SERIAL NOT NULL,
  CD_PESSOA_FISICA INTEGER NOT NULL,
  CD_USUARIO_HABILITA INTEGER NOT NULL,
  LOGIN VARCHAR(20) NULL,
  SENHA VARCHAR(100) NULL,
  IE_STATUS CHAR(1) NULL,
  PRIMARY KEY(CD_USUARIO)
);

ALTER TABLE USUARIO_TB ADD CONSTRAINT PF_FK_USUARIO FOREIGN KEY(CD_PESSOA_FISICA) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE USUARIO_TB ADD CONSTRAINT USU_FK_USUARIO FOREIGN KEY(CD_USUARIO_HABILITA) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE SETOR_TB ADD CONSTRAINT CONDOMINIO_FK_SETOR FOREIGN KEY(CD_CONDOMINIO) REFERENCES CONDOMINIO_TB(CD_CONDOMINIO);

ALTER TABLE SERVICO_ADICIONAL_TB ADD CONSTRAINT OS_FK_SERVICOADD FOREIGN KEY(CD_ORDEM_SERVICO) REFERENCES ORDEM_SERVICO_TB(CD_ORDEM_SERVICO);

ALTER TABLE RELACIONADOS_TB ADD CONSTRAINT PF1_FK_RELACIONADOS FOREIGN KEY(CD_PESSOA_FISICA_1) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE RELACIONADOS_TB ADD CONSTRAINT PF2_FK_RELACIONADOS FOREIGN KEY(CD_PESSOA_FISICA_2) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE PREDIO_TB ADD CONSTRAINT SETOR_FK_PREDIO FOREIGN KEY(CD_SETOR) REFERENCES SETOR_TB(CD_SETOR);

ALTER TABLE PJ_ENDERECO_TB ADD CONSTRAINT PJ_FK_PJEND FOREIGN KEY(CD_CGC) REFERENCES PESSOA_JURIDICA_TB(CD_CGC);

ALTER TABLE PJ_ENDERECO_TB ADD CONSTRAINT CATG_DM_FK_PJEND FOREIGN KEY(CD_CATG_END) REFERENCES CATEGORIA_TB(CD_CATEGORIA);

ALTER TABLE PJ_ENDERECO_TB ADD CONSTRAINT CATG_VL_FK_PJEND FOREIGN KEY(CD_CATG_END,CD_VL_CATG_END) REFERENCES CATEGORIA_VALOR_TB(CD_CATEGORIA,CD_VL_CATEGORIA);

ALTER TABLE PF_ENDERECO_TB ADD CONSTRAINT PF_FK_PFEND FOREIGN KEY(CD_PESSOA_FISICA) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE PF_ENDERECO_TB ADD CONSTRAINT CATG_VL_FK_PFEND FOREIGN KEY(CD_CATG_END,CD_VL_CATG_END) REFERENCES CATEGORIA_VALOR_TB(CD_CATEGORIA,CD_VL_CATEGORIA);

ALTER TABLE PESSOA_FISICA_TB ADD CONSTRAINT PJ_FK_PF FOREIGN KEY(CD_CGC) REFERENCES PESSOA_JURIDICA_TB(CD_CGC);

ALTER TABLE PESSOA_FISICA_TB ADD CONSTRAINT PROFISSAO_FK_PF FOREIGN KEY(CD_PROFISSAO) REFERENCES PROFISSAO_TB(CD_PROFISSAO);

ALTER TABLE ORDEM_SERVICO_TB ADD CONSTRAINT OCORRENCIA_FK_OS FOREIGN KEY(CD_OCORRENCIA) REFERENCES OCORRENCIA_TB(CD_OCORRENCIA);

ALTER TABLE ORDEM_SERVICO_TB ADD CONSTRAINT PF_EXE_FK_OS FOREIGN KEY(CD_PF_EXECUTOR) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE ORDEM_SERVICO_TB ADD CONSTRAINT PF_SOLC_FK_OS FOREIGN KEY(CD_PF_SOLICITANTE) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE ORCAMENTO_TB ADD CONSTRAINT OS_FK_ORCAMENTO FOREIGN KEY(CD_ORDEM_SERVICO) REFERENCES ORDEM_SERVICO_TB(CD_ORDEM_SERVICO);

ALTER TABLE OCORRENCIA_TB ADD CONSTRAINT PF_FK_OCORRENCIA FOREIGN KEY(CD_PF_INFORMANTE) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE OCORRENCIA_PF_ENVOLVIDA_TB ADD CONSTRAINT PF_FK_OCORRE_PF_ENVOL FOREIGN KEY (CD_PESSOA_FISICA) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE OCORRENCIA_PF_ENVOLVIDA_TB ADD CONSTRAINT OCORRENCIA_FK_OCORRE_PF_ENVOL FOREIGN KEY (CD_OCORRENCIA) REFERENCES OCORRENCIA_TB(CD_OCORRENCIA);

ALTER TABLE MORADOR_ENDERECO_TB ADD CONSTRAINT PF_FK_MORADOR FOREIGN KEY (CD_PESSOA_FISICA) REFERENCES PESSOA_FISICA_TB(CD_PESSOA_FISICA);

ALTER TABLE MORADOR_ENDERECO_TB ADD CONSTRAINT APARTAMENTO_FK_MORADOR FOREIGN KEY (CD_APARTAMENTO) REFERENCES APARTAMENTO_TB(CD_APARTAMENTO);

ALTER TABLE ITENS_ORCAMENTO_TB ADD CONSTRAINT PJ_FK_ITENS FOREIGN KEY (CD_CGC) REFERENCES PESSOA_JURIDICA_TB(CD_CGC);

ALTER TABLE ITENS_ORCAMENTO_TB ADD CONSTRAINT ORCAMENTO_FK_ITENS FOREIGN KEY (CD_ORCAMENTO) REFERENCES ORCAMENTO_TB(CD_ORCAMENTO);

ALTER TABLE CATEGORIA_VALOR_TB ADD CONSTRAINT CATG_DM_FK_CATG_VL FOREIGN KEY (CD_CATEGORIA) REFERENCES CATEGORIA_TB(CD_CATEGORIA);

ALTER TABLE APARTAMENTO_TB ADD CONSTRAINT PREDIO_FK_APARTAMENTO FOREIGN KEY (CD_PREDIO) REFERENCES PREDIO_TB(CD_PREDIO);


----------------------------- Tabelas de Logs ------------------------------


CREATE TABLE APARTAMENTO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_APARTAMENTO INTEGER NOT NULL,
  CD_PREDIO INTEGER NOT NULL,
  DESC_APARTAMENTO VARCHAR(10) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE CATEGORIA_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_CATEGORIA INTEGER NOT NULL,
  DESC_CATEGORIA VARCHAR(50) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE CATEGORIA_VALOR_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_VL_CATEGORIA INTEGER NOT NULL,
  CD_CATEGORIA INTEGER NOT NULL,
  DESC_VL_CATG VARCHAR(25) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE CONDOMINIO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_CONDOMINIO INTEGER NOT NULL,
  NM_CONDOMINIO VARCHAR(50) NULL,
  CEP NUMERIC(8,0) NULL,
  RUA VARCHAR(50) NULL,
  NUMERO INTEGER NULL,
  BAIRRO VARCHAR(50) NULL,
  CIDADE VARCHAR(25) NULL,
  ESTADO VARCHAR(25) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE ITENS_ORCAMENTO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  NR_SEQUENCIA INTEGER NOT NULL,
  CD_ORCAMENTO INTEGER NOT NULL,
  CD_CGC INTEGER NOT NULL,
  DESC_ITEM VARCHAR(50) NULL,
  QT_ITEM INTEGER NULL,
  VALOR_UNIT NUMERIC(10,2) NULL,
  VALOR_TOTAL NUMERIC(10,2) NULL,
  IE_APROVADO CHAR(1) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE MORADOR_ENDERECO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  NR_SEQUENCIA INTEGER NOT NULL,
  CD_PESSOA_FISICA INTEGER NOT NULL,
  CD_APARTAMENTO INTEGER NOT NULL,
  DT_ENTRADA DATE NULL,
  DT_SAIDA DATE NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE OCORRENCIA_PF_ENVOLVIDA_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_OCORRENCIA INTEGER NOT NULL,
  CD_PESSOA_FISICA INTEGER NOT NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE OCORRENCIA_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_OCORRENCIA INTEGER NOT NULL,
  CD_PF_INFORMANTE INTEGER NOT NULL,
  DESC_ASSUNTO VARCHAR(50) NULL,
  DESC_OCORRENCIA TEXT NULL,
  DT_OCORRENCIA DATE NULL,
  IE_SITUACAO CHAR(1) NULL,
  DESC_CONCLUSAO TEXT NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE ORCAMENTO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_ORCAMENTO INTEGER NOT NULL,
  CD_ORDEM_SERVICO INTEGER NOT NULL,
  DT_ORCAMENTO DATE NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE ORDEM_SERVICO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_ORDEM_SERVICO INTEGER NOT NULL,
  CD_OCORRENCIA INTEGER NOT NULL,
  CD_PF_EXECUTOR INTEGER NOT NULL,
  CD_PF_SOLICITANTE INTEGER NOT NULL,
  DESC_ASSUNTO VARCHAR(50) NULL,
  DESC_ORDEM_SERVICO TEXT NULL,
  DT_INICIO DATE NULL,
  DT_FIM DATE NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE PESSOA_FISICA_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_PESSOA_FISICA INTEGER NOT NULL,
  CD_CGC INTEGER NOT NULL,
  CD_PROFISSAO INTEGER NOT NULL,
  NM_PESSOA_FISICA VARCHAR(50) NULL,
  CPF NUMERIC(11,0) NULL,
  RG VARCHAR(15) NULL,
  ORG_RG CHAR(2) NULL,
  EMAIL VARCHAR(30) NULL,
  DDD_FONE NUMERIC(2,0) NULL,
  FONE NUMERIC(8,0) NULL,
  DDD_CELULAR NUMERIC(2,0) NULL,
  CELULAR NUMERIC(9,0) NULL,
  DT_NASCIMENTO DATE NULL,
  IE_SEXO CHAR(1) NULL,
  IM_FOTO OID NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE PESSOA_JURIDICA_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_CGC INTEGER NOT NULL,
  NM_FANTASIA VARCHAR(50) NULL,
  DESC_RAZAO VARCHAR(50) NULL,
  DESC_ATIVIDADE TEXT NULL,
  EMAIL VARCHAR(30) NULL,
  DDD_FONE NUMERIC(2,0) NULL,
  FONE NUMERIC(8,0) NULL,
  DDD_FAX NUMERIC(2,0) NULL,
  FONE_FAX NUMERIC(8,0) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE PF_ENDERECO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  NR_SEQUENCIA INTEGER NOT NULL,
  CD_CATG_END INTEGER NOT NULL,
  CD_VL_CATG_END INTEGER NOT NULL,
  CD_PESSOA_FISICA INTEGER NOT NULL,
  CEP NUMERIC(8,0) NULL,
  RUA VARCHAR(50) NULL,
  NUMERO INTEGER NULL,
  BAIRRO VARCHAR(25) NULL,
  CIDADE VARCHAR(25) NULL,
  ESTADO VARCHAR(25) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE PJ_ENDERECO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  NR_SEQUENCIA INTEGER NOT NULL,
  CD_CATG_END INTEGER NOT NULL,
  CD_VL_CATG_END INTEGER NOT NULL,
  CD_CGC INTEGER NOT NULL,
  CEP NUMERIC(8,0) NULL,
  RUA VARCHAR(50) NULL,
  NUMERO INTEGER NULL,
  BAIRRO VARCHAR(25) NULL,
  CIDADE VARCHAR(25) NULL,
  ESTADO VARCHAR(25) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE PREDIO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_PREDIO INTEGER NOT NULL,
  CD_SETOR INTEGER NOT NULL,
  DESC_PREDIO VARCHAR(10) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE PROFISSAO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_PROFISSAO INTEGER NOT NULL,
  NM_PROFISSAO VARCHAR(50) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE RELACIONADOS_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_PESSOA_FISICA_2 INTEGER NOT NULL,
  CD_PESSOA_FISICA_1 INTEGER NOT NULL,
  CD_CATG_RELAC INTEGER NOT NULL,
  CD_VL_CATG_RELAC INTEGER NOT NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE SERVICO_ADICIONAL_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_SERV_ADICIONAL INTEGER NOT NULL,
  CD_ORDEM_SERVICO INTEGER NOT NULL,
  DT_INICIO DATE NULL,
  DT_FIM INTEGER NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE SETOR_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL,
  CD_SETOR INTEGER NOT NULL,
  CD_CONDOMINIO INTEGER NOT NULL,
  NM_SETOR VARCHAR(50) NULL,
  OBSERVACAO TEXT NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);

CREATE TABLE USUARIO_LOG_TB (
  NR_SEQ_LOG SERIAL NOT NULL,
  USU_EXECUTOR INTEGER NOT NULL,
  IE_COMANDO CHAR(1) NOT NULL,
  DT_EXECUSAO DATE NOT NULL, 		
  CD_USUARIO INTEGER NOT NULL,
  CD_PESSOA_FISICA INTEGER NOT NULL,
  CD_USUARIO_HABILITA INTEGER NOT NULL,
  LOGIN VARCHAR(20) NULL,
  SENHA VARCHAR(100) NULL,
  IE_STATUS CHAR(1) NULL,
  PRIMARY KEY(NR_SEQ_LOG)
);


ALTER TABLE USUARIO_LOG_TB ADD CONSTRAINT USU_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE SETOR_LOG_TB ADD CONSTRAINT SETOR_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE SERVICO_ADICIONAL_LOG_TB ADD CONSTRAINT SERV_ADD_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE RELACIONADOS_LOG_TB ADD CONSTRAINT RELACIONADOS_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE PROFISSAO_LOG_TB ADD CONSTRAINT PROFISSAO_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE PREDIO_LOG_TB ADD CONSTRAINT PREDIO_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE PJ_ENDERECO_LOG_TB ADD CONSTRAINT PJ_END_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE PF_ENDERECO_LOG_TB ADD CONSTRAINT PF_END_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE PESSOA_JURIDICA_LOG_TB ADD CONSTRAINT PJ_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE PESSOA_FISICA_LOG_TB ADD CONSTRAINT PF_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE ORDEM_SERVICO_LOG_TB ADD CONSTRAINT OS_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE ORCAMENTO_LOG_TB ADD CONSTRAINT ORCAMENTO_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE OCORRENCIA_LOG_TB ADD CONSTRAINT OCORRENCIA_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE OCORRENCIA_PF_ENVOLVIDA_LOG_TB ADD CONSTRAINT OCORRENCIA_ENV_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE MORADOR_ENDERECO_LOG_TB ADD CONSTRAINT MORADOR_END_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE ITENS_ORCAMENTO_LOG_TB ADD CONSTRAINT ITENS_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE CONDOMINIO_LOG_TB ADD CONSTRAINT CONDOMINIO_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE CATEGORIA_VALOR_LOG_TB ADD CONSTRAINT CATG_VL_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE CATEGORIA_LOG_TB ADD CONSTRAINT CATG_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);

ALTER TABLE APARTAMENTO_LOG_TB ADD CONSTRAINT APARTAMENTO_LOG_FK_USU FOREIGN KEY(USU_EXECUTOR) REFERENCES USUARIO_TB(CD_USUARIO);


